num = ARGV[0].to_i

if (num >=1 )
    puts "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras interdum malesuada purus, ac mollis eros aliquam ac. Nam in ex eget libero fermentum finibus vitae quis tortor. Curabitur dapibus cursus maximus. Etiam vestibulum, ligula non rutrum ullamcorper, ipsum nunc sagittis tellus, eget rhoncus mi ex ac felis. In auctor quam vel enim rutrum, vel vestibulum elit suscipit. Vivamus elementum finibus tellus at hendrerit. In quis ex at orci molestie rhoncus. Sed et diam turpis. Duis non est tincidunt, condimentum dui vitae, rutrum leo."
elsif (num >=2)
    puts "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras interdum malesuada purus, ac mollis eros aliquam ac. Nam in ex eget libero fermentum finibus vitae quis tortor. Curabitur dapibus cursus maximus. Etiam vestibulum, ligula non rutrum ullamcorper, ipsum nunc sagittis tellus, eget rhoncus mi ex ac felis. In auctor quam vel enim rutrum, vel vestibulum elit suscipit. Vivamus elementum finibus tellus at hendrerit. In quis ex at orci molestie rhoncus. Sed et diam turpis. Duis non est tincidunt, condimentum dui vitae, rutrum leo.

    Praesent vel fermentum nisl. Vestibulum quis nibh in nisi faucibus rutrum eu sit amet elit. Mauris erat erat, gravida at vestibulum quis, ultrices eu orci. Phasellus eget risus aliquet, semper est id, imperdiet arcu. Praesent tincidunt id massa eu commodo. Nullam nec sagittis felis. Nam fermentum, ex auctor pharetra aliquet, nibh lorem viverra elit, quis rutrum nibh tortor at odio. Praesent tincidunt lectus vel dolor aliquet, eleifend aliquet mauris ullamcorper. Nam id nisl aliquet, interdum nunc sed, cursus felis. Praesent rutrum elit id lobortis rutrum. Proin dapibus tortor eget ante rutrum, vitae aliquet nulla faucibus. Integer elementum purus vitae leo aliquet posuere volutpat quis risus. Sed porta justo et justo tristique rhoncus. Duis ornare laoreet ullamcorper. Suspendisse imperdiet nisl eget lacus laoreet, sit amet cursus felis ultricies."
elsif (num >=3)
    puts "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras interdum malesuada purus, ac mollis eros aliquam ac. Nam in ex eget libero fermentum finibus vitae quis tortor. Curabitur dapibus cursus maximus. Etiam vestibulum, ligula non rutrum ullamcorper, ipsum nunc sagittis tellus, eget rhoncus mi ex ac felis. In auctor quam vel enim rutrum, vel vestibulum elit suscipit. Vivamus elementum finibus tellus at hendrerit. In quis ex at orci molestie rhoncus. Sed et diam turpis. Duis non est tincidunt, condimentum dui vitae, rutrum leo.

    Praesent vel fermentum nisl. Vestibulum quis nibh in nisi faucibus rutrum eu sit amet elit. Mauris erat erat, gravida at vestibulum quis, ultrices eu orci. Phasellus eget risus aliquet, semper est id, imperdiet arcu. Praesent tincidunt id massa eu commodo. Nullam nec sagittis felis. Nam fermentum, ex auctor pharetra aliquet, nibh lorem viverra elit, quis rutrum nibh tortor at odio. Praesent tincidunt lectus vel dolor aliquet, eleifend aliquet mauris ullamcorper. Nam id nisl aliquet, interdum nunc sed, cursus felis. Praesent rutrum elit id lobortis rutrum. Proin dapibus tortor eget ante rutrum, vitae aliquet nulla faucibus. Integer elementum purus vitae leo aliquet posuere volutpat quis risus. Sed porta justo et justo tristique rhoncus. Duis ornare laoreet ullamcorper. Suspendisse imperdiet nisl eget lacus laoreet, sit amet cursus felis ultricies.

    Sed ligula eros, tincidunt at tempus et, vulputate non metus. Ut vitae tellus risus. Phasellus urna dolor, pretium quis nunc at, ultricies porta lorem. Nullam tincidunt cursus massa, sed sollicitudin ligula consequat ac. Pellentesque sem enim, dignissim nec mattis at, fermentum nec magna. Mauris a aliquet lorem. Nam pulvinar quam sit amet leo bibendum dapibus. Ut at aliquet arcu. Curabitur volutpat lectus sit amet aliquam rutrum."
elsif (num >=4)
    puts "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras interdum malesuada purus, ac mollis eros aliquam ac. Nam in ex eget libero fermentum finibus vitae quis tortor. Curabitur dapibus cursus maximus. Etiam vestibulum, ligula non rutrum ullamcorper, ipsum nunc sagittis tellus, eget rhoncus mi ex ac felis. In auctor quam vel enim rutrum, vel vestibulum elit suscipit. Vivamus elementum finibus tellus at hendrerit. In quis ex at orci molestie rhoncus. Sed et diam turpis. Duis non est tincidunt, condimentum dui vitae, rutrum leo.

    Praesent vel fermentum nisl. Vestibulum quis nibh in nisi faucibus rutrum eu sit amet elit. Mauris erat erat, gravida at vestibulum quis, ultrices eu orci. Phasellus eget risus aliquet, semper est id, imperdiet arcu. Praesent tincidunt id massa eu commodo. Nullam nec sagittis felis. Nam fermentum, ex auctor pharetra aliquet, nibh lorem viverra elit, quis rutrum nibh tortor at odio. Praesent tincidunt lectus vel dolor aliquet, eleifend aliquet mauris ullamcorper. Nam id nisl aliquet, interdum nunc sed, cursus felis. Praesent rutrum elit id lobortis rutrum. Proin dapibus tortor eget ante rutrum, vitae aliquet nulla faucibus. Integer elementum purus vitae leo aliquet posuere volutpat quis risus. Sed porta justo et justo tristique rhoncus. Duis ornare laoreet ullamcorper. Suspendisse imperdiet nisl eget lacus laoreet, sit amet cursus felis ultricies.

    Sed ligula eros, tincidunt at tempus et, vulputate non metus. Ut vitae tellus risus. Phasellus urna dolor, pretium quis nunc at, ultricies porta lorem. Nullam tincidunt cursus massa, sed sollicitudin ligula consequat ac. Pellentesque sem enim, dignissim nec mattis at, fermentum nec magna. Mauris a aliquet lorem. Nam pulvinar quam sit amet leo bibendum dapibus. Ut at aliquet arcu. Curabitur volutpat lectus sit amet aliquam rutrum.

    In blandit imperdiet lacus, sed scelerisque tortor viverra in. Phasellus blandit convallis elementum. Aenean tincidunt justo eu consectetur euismod. Proin ultricies a ante eu consectetur. Sed dapibus euismod ante. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla consequat, tellus quis pellentesque dapibus, orci tortor posuere justo, vel ultricies libero dui nec massa. Donec leo enim, consequat a interdum a, egestas quis felis. Donec tincidunt commodo facilisis. Vestibulum posuere libero a convallis tempor. Sed justo mauris, mollis at urna maximus, consequat semper ex."
end
